### PR TITLE
Continuous deployment

### PR DESCRIPTION
**Pull request by avirshup**
Gets CD working

### CODE REVIEW

**Comment by justinmc** [comment]
Does this mean any merge to master will automatically be deployed?

**Comment by avirshup** [comment]
@justinmc - nope, only commits tagged with valid version numbers will be deployed.

**Comment by justinmc** [comment]
Cool that's probably even better 👍

**Comment by avirshup** [comment]
@justinmc - probably I meant to call this "automated deployment" :)

**Pull request merged**
