### PR TITLE
Residue Selection RPC Removal

### PR DESCRIPTION
**Pull request by justinmc**
This PR will get Residue Selector to work with data binding.

### CODE REVIEW

**Comment by justinmc** [comment]
residue_selector

**Comment by justinmc** [comment]
@avirshup This is ready for review!  This will go into a feature branch (https://github.com/Autodesk/molecular-design-toolkit/pull/82) instead of going directly into master, as we discussed.

Also, there is a bug where unselecting the final atom doesn't work.  I believe this is a bug in ipywidgets though, and I submitted a PR to fix it [here](https://github.com/ipython/ipywidgets/pull/739).  That should fix the bug in our project whenever it gets merged and we upgrade ipywidgets.

**Comment by avirshup** [comment]
Awesome! Checking it out now.

The MDT python 3 transition hasn't really started yet, so this should at least go into `dev` soon - does this depend on a specific commit or branch in `nbmolviz`?

**Comment by justinmc** [comment]
Yeah merging this right now would definitely break the selector if not more.  It depends on [this unfinished nbmolviz PR to abstract nbmolviz3d](https://github.com/Autodesk/notebook-molecular-visualization/pull/9), which also needs the nbmolviz3d open source project and npm module.  I planned to merge all of these RPC PRs into https://github.com/Autodesk/molecular-design-toolkit/pull/82 and then merge them all when everything is ready.

Does it seem like these kinds of changes will result in big conflicts with the Python 3 transition?  Hopefully I can hurry this up and get all the nbmolviz3d stuff in before it starts, but it's a huge bunch of changes that can't be split up unfortunately.

**Pull request merged**
