### PR TITLE
Deployment fixes

### PR DESCRIPTION
**Pull request by avirshup**
Hey @dionjwa, this addresses #107. Could you do a quick review?

### CODE REVIEW

**Comment by dionjwa** [comment]
This builds ok with `docker build -t mdt .`, but when I try
```
docker run --rm  -p 8888:8888 mdt python -m moldesign intro
```
but I get:
```
/usr/bin/python: No module named bondclicker; 'moldesign' is a package and cannot be directly executed
```

**Comment by dionjwa** [comment]
Maybe you should have a `CMD` entry so that there is a sensible default to start the container?

**Comment by avirshup** [comment]
`/usr/bin/python: No module named bondclicker; 'moldesign' is a package and cannot be directly executed` - this is a silly bug that my local tests weren't catching because of stale `.pyc` files. It's fixed in our travis branch, will merge it over here soon ...

**Comment by avirshup** [comment]
Hey @dionjwa - this should work. Can you test it quickly?

Assuming you've already got this branch locally:
```
cd molecular-design-toolkit
git checkout deployment_fixes
git pull

docker build . -t mdtdocker
```

To start a notebook server on port 9000:
```
docker run -it -p 9000:8888 mdtdocker
```

Or to just shell into it:
```
docker run -it mdtdocker bash
```

Thanks!

**Comment by avirshup** [comment]
@dionjwa - I think this should work for you now, please give it a shot! To bring up a ready-to-go jupyter server on port 9000, first pull the `deployment_fixes` branch, then run:
```
cd molecular-design-toolkit
git pull [origin/upstream/whatever] deployment_fixes
docker build . -t mdtdocker
docker run -it -p 9000:8888 mdtdocker
```

You can just use `docker run -it mdtdocker bash` if you want to play with the image with a CLI.

**Comment by dionjwa** [comment]
This works for me.

**Comment by avirshup** [comment]
Thanks!

**Pull request merged**
