### PR TITLE
Support Data-Bound nbmolviz3d

### PR DESCRIPTION
**Pull request by justinmc**
This PR will remove RPC-related code and replace it with data interactions.  For supporting [this notebook-molecular-visualization PR](https://github.com/Autodesk/notebook-molecular-visualization/pull/9).

I am working through this by sequentially getting the WidgetList.ipynb widgets to work without RPC.  Here is my progress:

 - [x] Small molecule visualizer
 - [x] Large molecule visualizer
    - This one has a mix of cartoon and ball-and-stick styles in one view.  I got this to work by allowing styles to be passed individually for every atom.
 - [x] Symmetrizer.
    - Got shapes working by adding a "shape" parameter (meaning only 1 shape at a time can be active now).
 - [x] Residue selector
    - Added a `selection_type` parameter to indicate atom, residue, or chain.
 - [x] Bond selector
    - A bond is selected with both the atoms it joins are selected.  This is a temporary simplified and limited form from the earlier version where clickable shapes were drawn over the bonds.
 - [x] Geometry builder
    - Neighbor atoms in a dihedral atoms are not colored like they were in the original.
 - [x] Orbital visualizer
    - The displayed orbitals seem to differ from the original in strange ways...
 - [x] Trajectory viewer
    - No PR here was needed for this, only this commit in notebook-molecular-visualization: https://github.com/Autodesk/notebook-molecular-visualization/pull/9/commits/2c704b3592605b5623b39d2633ce9f20a125d99d
 - [x] Trajectory orbital viewer
     - No PR here was needed for this, only this commit in notebook-molecular-visualization: https://github.com/Autodesk/notebook-molecular-visualization/pull/9/commits/64cf88b657184036d77307601bdca27bd106dd61
 - [x] Forcefield assignment viewer
    - Some color differences and lack of a residue label.

### CODE REVIEW

**Comment by justinmc** [comment]
Steps to run this before anything is merged:

  1. Checkout this branch.
  1. Checkout the branch [webpage-useable-3d](https://github.com/Autodesk/notebook-molecular-visualization/pull/9) in the notebook-molecular-visualization project
  1. Checkout [json-sync](https://git.autodesk.com/mccandj/nbmolviz3d/pull/1) in the nbmolviz3d project (soon to be open sourced)
  1. Build nbmolviz3d (`npm run build`).
  1. Link your nbmolviz3d to your notebook-molecular-visualization (run `npm link` in the nbmolviz3d root directory, then run `npm link nbmolviz3d` in notebook-molecular-visualization's js directory).
  1. Run `npm install` in notebook-molecular-visualization
  1. Rebuild the notebook-molecular-visualization js (`python setup.py jsdeps`)
  1. Run mdt!  `python -m moldesign intro`

**Comment by justinmc** [comment]
@avirshup Take a look at my installation instructions above.  It seems more complicated that I thought to run this right now :)  Let me know if you want me to help you get set up.

Also I added checkboxes at the top with my progress.  Hopefully the trajectory and forcefield stuff isn't super different than everything else, if so I'm on pretty good track.

**Comment by avirshup** [comment]
I'll start listing issues I get when running through the WidgetList notebook:

`small_molecule.draw()` produces a TypeError:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-1670f76d8578> in <module>()
----> 1 small_molecule.draw()

/Users/aaronvirshup/other_code/jsonrpc/test/moldesign/molecules/atomcollections.pyc in draw(self, width, height, show_2dhydrogens, display)
    241             viz3d = self.draw3d(width=width, height=height,
    242                                 display=False)
--> 243             link((viz3d, 'selected_atom_indices'), (viz2d, 'selected_atom_indices'))
    244             views = ipy.HBox([viz2d, viz3d])
    245         else:

/usr/local/lib/python2.7/site-packages/traitlets/traitlets.pyc in __init__(self, source, target)
    237 
    238     def __init__(self, source, target):
--> 239         _validate_link(source, target)
    240         self.source, self.target = source, target
    241         try:

/usr/local/lib/python2.7/site-packages/traitlets/traitlets.pyc in _validate_link(*tuples)
    217             raise TypeError("Each object must be HasTraits, not %r" % type(obj))
    218         if not trait_name in obj.traits():
--> 219             raise TypeError("%r has no trait %r" % (obj, trait_name))
    220 
    221 

TypeError: <moldesign.viewer.viewer3d.GeometryViewer object at 0x109c15f90> has no trait 'selected_atom_indices'
```

**Comment by avirshup** [comment]
Protein visualization: rendering and style changing (i.e. `viewer.sphere(atoms=[atom1, atom2...])`) work well. However, clicking on atoms doesn't do anything; in the stable version, clicking will highlight it and trigger a text display below the window:

image

Is this because because we're waiting for the UX redesign?

**Comment by avirshup** [comment]
Symmetrizer: Works well, but a minor issue is that the molecule isn't rotating about its center.
symmetrizer

I think this can be fixed just by calling `Symmetrizer.viewer.center()`

**Comment by avirshup** [comment]
ResidueSelector raises an exception:

```python
residue_selector = mdt.widgets.selection.ResidueSelector(protein)
residue_selector
```

Produces
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-74f913a54cf5> in <module>()
----> 1 residue_selector = mdt.widgets.selection.ResidueSelector(protein)
      2 residue_selector

/Users/aaronvirshup/other_code/jsonrpc/test/moldesign/widgets/selection.pyc in __init__(self, mol)
     92     """
     93     def __init__(self, mol):
---> 94         super(ResidueSelector, self).__init__(mol)
     95 
     96         self._residue_selection = collections.OrderedDict()

/Users/aaronvirshup/other_code/jsonrpc/test/moldesign/uibase/components.pyc in __init__(self, mol)
     89 
     90         self.atom_listname = ipy.HTML('<b>Selected atoms:</b>')
---> 91         self.atom_list = ipy.SelectMultiple(options=list(self.viewer.selected_atoms), height=150)
     92         traitlets.directional_link(
     93             (self.viewer, 'selected_atoms'),

AttributeError: 'GeometryViewer' object has no attribute 'selected_atoms'
```

**Comment by avirshup** [comment]
BondSelector also raises an exception:

```python
bondselector = mdt.widgets.BondSelector(small_molecule)
bondselector
```
produces
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-30-487d08a3a76b> in <module>()
----> 1 bondselector = mdt.widgets.BondSelector(small_molecule)
      2 bondselector

/Users/aaronvirshup/other_code/jsonrpc/test/moldesign/widgets/selection.pyc in __init__(self, mol)
     32 
     33     def __init__(self, mol):
---> 34         super(BondSelector, self).__init__(mol)
     35 
     36         self._bondset = collections.OrderedDict()

/Users/aaronvirshup/other_code/jsonrpc/test/moldesign/uibase/components.pyc in __init__(self, mol)
     89 
     90         self.atom_listname = ipy.HTML('<b>Selected atoms:</b>')
---> 91         self.atom_list = ipy.SelectMultiple(options=list(self.viewer.selected_atoms), height=150)
     92         traitlets.directional_link(
     93             (self.viewer, 'selected_atoms'),

AttributeError: 'BondClicker' object has no attribute 'selected_atoms'
```

**Comment by avirshup** [comment]
Works perfectly:
`small_molecule.draw_orbitals()`
`traj.draw()`
`traj.draw_orbitals()`
`ParameterizationDisplay`

**Comment by avirshup** [comment]
Note that the "black-window" bug (#68) is still alive after these changes, but I've at least come up with a way to reproduce it.

**Comment by justinmc** [comment]
I'm consolidating these into a checkbox list for me to go through, with comments when needed:

  - [x] small_molecule.draw() produces a TypeError
    - I'm not getting this myself.  May have to do with installation, I'll look into it if we see it again after I fix these.
  - [x] Selection not working
    - This should have been working except for the text display under the visualization.  I just fixed it so that should display too.
  - [ ] Symmetrizer not rotating about its center
  - [ ] Residue selector exception
  - [ ] Bond selector exception

**Comment by justinmc** [comment]
@avirshup Can you run through your points one more time when you get a chance and let me know if they seem fixed to you?

**Comment by avirshup** [comment]
@justinmc - will do! Should I pull from master on `notebook-molecular-visualization` and `nbmolviz3d`?

Also, try this to reproduce the Symmetrizer off-center problem:

```python
import moldesign as mdt
from moldesign import units as u

mol = mdt.from_smiles('C=C')
for atom in mol.atoms:
    atom.x += 4.0 * u.angstrom

mdt.widgets.Symmetrizer(mol)
```

**Comment by justinmc** [comment]
@avirshup Thank you!  Yeah pull from master on those and from this branch in this repo.  I'll try the symmetrizer thing again.

**Comment by avirshup** [comment]
**Notes on the test run as of commit d3dabf7**

I can't reproduce the off-center Symmetrizer bug anymore, so it's apparently fixed :)

## Improvements
1. `small_molecule.draw2d()`: looks nicer, performs better
2. `small_molecule.draw3d()`: selections now toggle instead of being 1-at-a-time. I actually like it better this way.
3. `small_molecule.draw()`, `protein.draw()`: The transition from showing 1 atom's text info to multiple atoms' text info is _great_.
4. `GeometryBuilder`: WAY more responsive. Really like how the view auto-adjusts!

## Major issues

1. `small_molecule.draw()` - Clicking on the 2D drawing doesn't do anything. The 2D drawing doesn't display any selections. image
3. `set_color` method and `color` keyword arguments don't appear to work for shapes or atom representations
4. `draw_sphere`, `draw_cylinder`, etc.:
  - will delete any previously drawn objects when called - i.e., it only displays one shape at a time
  - aren't respecting their keyword arguments (`radius`, `color`, `opacity` etc.)
7. `ResidueSelector` - UI works well, but `residue_selector.selected_residues` remains empty
8. `small_molecule.draw_orbitals()` - The isovalue in the 3D rendering appears stuck at 0
9. `trajectory.draw()`, `trajectory.draw_orbitals()` both raise `NotImplementedError` when called

**Comment by avirshup** [comment]
## Minor issues
*Minor issues*

1. `small_molecule.draw()`: I like the ability to toggle selections and to immediately get `selected_atom_indices`; but it needs to be easier to identify any single atom. (this may be addressed in the new UI work). In the text display, we should always display the list indices for the chains, residues, and atoms too.
1. `GeometryBuilder` - drawing a green bond for some reason image
3. `protein.draw3d()` - without the `render` keyword, we sometimes see visualization changes "pop in" individually. ![autostyle] (https://cloud.githubusercontent.com/assets/9388007/18568961/bbfc849c-7b54-11e6-9350-94b57046dad6.gif) This could be bad in cases where a routine is trying to show a very specific view to a user. Long term, it would be good to offer a context manager to prevent intermediate 3D redraws, e.g.,
```python
viewer = protein.draw()
with viewer.hold_redraw():
   viewer.do_something()  # viewer doesn't update
   viewer.do_somethingelse()  # viewer still doesn't update
# NOW the viewer updates
```

**Comment by justinmc** [comment]
More checkboxes to keep track of these bugs:

Major:
  1. [ ] The 2d visualization works for me (I'm able to select things, and it syncs with the 3d visualization).  It could be that I forgot to merge something to master though...  I'll check this out on your computer if it's still happening.
  1. [ ]
  1. [ ] I originally only supported drawing 1 shape at a time for simplicity, because I never needed more than one shape for the widgets in WidgetList.ipynb.  Sounds like we need to support drawing any arbitrary shapes though, which I can add.
  1. [ ]
  1. [ ]
  1. [ ]

Minor:
  1. [ ]
  1. [ ]
  1. [ ]

**Comment by justinmc** [comment]
@avirshup Can you run this again and let me know if I fixed everything when you get a chance?  I believe I fixed everything except for the pop in issue (minor #3).  Use the branch `rpc-cleanup` in notebook-molecular-visualization.

**Comment by avirshup** [comment]
Hey @mccandj - we're getting there! I think we're down to 4 issues - most of which we should go over in person, since it looks like we're getting different behavior :)

`v = small_molecule.draw(display=True)`
- The text description should disappear (or read 'no selection' or something) when all atoms are deselected - right now, the last selection remains visible
- 2D selection still isn't working on my machine
- Nothing happens when setting atom colors (using `v.set_color` or `v.sphere(color='red')`) (spheres, arrows, etc. work fine)

`small_molecule.draw_orbitals()`
- The orbital isovalues still aren't working on my machine

**Comment by justinmc** [comment]
Checklist:

  - [ ] `set_color` and `sphere` are changing the styles (not drawing shapes), so this is a legitimate bug that should be fixed.
  - [ ] isoValue slider should be drawing a new shape altogether whenever it changes (also make sure keyword arguments for colors and opacity of orbitals are working)

**Comment by justinmc** [comment]
@avirshup I think I fixed those two points.  The orbitals visualizer makes a lot more sense now that I fixed the isoval thing haha.  Pull the `rpc-cleanup` branch on notebook-molecular-visualization and you should be good to go.

**Comment by justinmc** [comment]
@avirshup I'll need your help getting master running when you get back.  I'm unable to run master, so after merging master into this branch, I'm unable to run this as well.

**Comment by justinmc** [comment]
@avirshup I'm getting this error when trying to run forecefield assignment after merging this with master, any idea what would cause it?

```
---------------------------------------------------------------------------
ParameterizationError                     Traceback (most recent call last)
<ipython-input-3-fb5b5d5d27aa> in <module>()
----> 1 mdt.assign_forcefield(protein)

/Users/mccandj/Projects/molecular-design-toolkit/moldesign/interfaces/ambertools.pyc in assign_forcefield(mol, **kwargs)
    275         return newmol
    276     else:
--> 277         raise ParameterizationError('TLeap failed to assign force field parameters for %s' % mol, job)
    278 
    279 

ParameterizationError: ('TLeap failed to assign force field parameters for Molecule: 3aid', <Job "tleap, 3aid" status:Finished jobid:7aa04c28f211d33d9d5c32d6fdd2445825df8ff4cbdf5f448e80afab26ea5133 engine:Docker host:http+docker://localunixsocket>)
```

That's when running:

```
import numpy as np
import moldesign as mdt
mdt.compute.config.engine_type = 'docker'
protein = mdt.from_pdb('3aid')
mdt.assign_forcefield(protein)
```

Otherwise I think this is good to go...  Conflicts with master weren't too bad, and everything else seems to still be working.

**Comment by avirshup** [comment]
That's actually the expected behavior, so this looks good!

**Comment by justinmc** [comment]
@avirshup Oh great haha.  What's our strategy for merging this then?  Is it alright to go into master?  I'll also need to merge [this notebook-molecular-visualiztion](https://github.com/Autodesk/notebook-molecular-visualization/pull/21) PR at the same time.

**Comment by avirshup** [comment]
I think it makes sense to merge these into master now, for both projects. It will probably take a little time to make sure everything is stable after that. Once that's done, I'll run through all the tests and examples in the _moldesign_examples directory and start figuring out if anything else needs to be fixed before 0.7.4.

**Comment by justinmc** [comment]
@avirshup Sounds good, I'll go ahead and merge these.  Let me know if anything starts breaking! 🍀

**Pull request merged**
