### PR TITLE
Parmed integration

### PR DESCRIPTION
**Pull request by avirshup**
This adds integrations for the ParmEd package, which provides the best python mmCIF/PDB parsers that I've been able to find so far - and provides fixes most of our failing test cases. Note that this is branched on #115, so that should get merged first.

It introduces yet another python package dependency, but it's easy enough to install that we can just stick with pip/conda.

ParmEd's real power comes in giving us a piece that we've been missing for a while - abstracted, introspectable force field objects. Those will be integrated in an upcoming PR.

### CODE REVIEW

**Comment by avirshup** [comment]
@ktbolt @justinmc - this one is now ready for review.

**Comment by ktbolt** [comment]
I see comments referring to Biopython, like "Parse an mmCIF file (using the Biopython parser) ". Should this be changed to "ParmEd"?

There are some problems not using the author chain IDs for hetatoms I've found; ambiguities in residue IDs.

How do you handle errors in reading mmCIF files?

**Comment by avirshup** [comment]
Thanks for looking at this @ktbolt! I should definitely get the comments (and docstrings, I think) changed to reflect the new implementation we're using.

> There are some problems not using the author chain IDs for hetatoms I've found; ambiguities in residue IDs.

That's very good to know. The problem (you've probably dealt with this) is that the bioassemblies refer to chains using the "label chain ID", not the author id. How do you guys deal with this? Do you have any specific test cases we can add?

> How do you handle errors in reading mmCIF files?

We don't - it will just throw an exception.

**Comment by avirshup** [comment]
@ktbolt - I couldn't find a 14FZ - did you mean 1F4Z? If so, it looks like the ParmEd parser (with our fix to use `_atom_site.label_asym_id` for the chain instead of `_atom_site.auth_asym_id`) does indeed separate the residues correctly:

Running
```python
import moldesign as mdt
mol = mdt.from_pdb('1F4Z', usecif=True)
mol
```

yields:

image

Does this look like it deals with the problem correctly?

**Comment by avirshup** [comment]
@ktbolt - Also just realized we actually have a [test for the residue-splitting issue](https://github.com/Autodesk/molecular-design-toolkit/blob/ccec01293d9acca552401f39b2add93337ab7240/moldesign/_tests/test_protein_primary_structure.py#L47)

**Comment by ktbolt** [comment]
The MV does the same thing, puts all HOH into a single chain under a single residue ID 5 for the CIF file. The PDB file has the HOH in a single chain with a different residue ID for each molecule. 

I'm not sure if it is a problem but I wonder if there are H atoms with the O how to know which H go with which O? Distance checking I guess.

In the test you mentioned above, shouldn't mol.chains['D'].num_residue = 1? All the O and H atoms have the same residue ID. Or are you looking at the auth_seq_id?

**Comment by avirshup** [comment]
@ktbolt: From looking at [ParmEd code](https://github.com/ParmEd/ParmEd/blob/027ce2854b2a1e92d7144628432dd911a176be1a/parmed/formats/pdb.py#L1153-L1167), I think it's using the `auth_seq_id` for all residue numbers, so that's why we're ending up with 25 separate waters in chain `Q`.

So MDT is indeed providing something a little weird - it's got new-style chain IDs from `_atom_site.label_asym_id` but old-style residue IDs from `_atom_site.label_asym_id`. I'm almost positive that *the correct way to split the waters* is to use the `_pdbx_nonpoly_scheme.ndb_seq_num` or _pdbx_nonpoly_scheme.pdb_seq_num` instead.

But I haven't found any parsers that do that (it might be time to write my own).

So, what do you think - should we merge this as is and wait to see if we run into problems? Or should I got back and parse mmCIF the right way?

**Comment by ktbolt** [comment]
I think it is fine to merge it.

**Comment by avirshup** [comment]
Merged after offline conversation and :+1: from @ktbolt. Thanks Dave!

**Pull request merged**
