### PR TITLE
0.7.3 release cleanup

### PR DESCRIPTION
**Pull request by avirshup**
This PR will collect commits as I try to automate as much of the release process as we finalize 0.7.3, and in preparation for CI/CD.

This will be almost entirely changes to configuration and packaging files. I'm specifically aiming to automate:
 1. docker image builds,
 1. testing in docker containers, and
 1. Testing/maintaining consistent version numbers across all of the following:
   - docker image tags,
   - in packages inside docker images,
   - pypi,
   - git,
   - python package metadata,
   - internal MDT configuration files

### CODE REVIEW

**Comment by avirshup** [comment]
@justinmc - this is ready to merge, and to become the official 0.7.3 release. I've now pushed the release candidate docker containers to dockerhub, so at least that part should be working.

To run the tests, you can run: `cd $REPO/moldesign/_tests && py.test`
I've verified that they work both on my local machine and in two docker environments, with and without various dependencies: `docker.io/autodesk/moldesign:moldesign_complete-0.7.3` and `docker.io/autodesk/moldesign:moldesign_minimal-0.7.3`

**Comment by avirshup** [comment]
@justinmc - interesting. What compute backend are you using? My guess is that this is something Docker or CCC related. Two things to try:
 - Make sure that `~/.moldesign/moldesign.yml` doesn't have anything other than `engine_type: XXX`
 - Upgrade `pyccc` with `pip install --upgrade pyccc`

If that doesn't work, please go ahead and upload the logs

**Comment by justinmc** [comment]
@avirshup I'm getting the same result.  I actually didn't have a /moldesign/moldesign.yml file at all, so I created it and added only the line:

    engine_type: CloudComputeCannon

Is that a valid value for that?  I also upgraded pyccc like you said, but I'm still getting the same 40 failures.

Here is the full output for `py.test -n 2`: http://pastebin.com/4f6VwDQr

**Comment by justinmc** [comment]
I just realized I'm unable to run master, and I get the same error that I see when I ran the tests here.  So my problems are probably due to that and not this branch.

**Comment by avirshup** [comment]
@justinmc - well, this is definitely something to do with the remote jobs. Looks to me like they might be running in old versions of the docker images. Probably fastest to debug in person - I'll post the result here for posterity :)

**Comment by avirshup** [comment]
We are basically ready to release this. Some notes for next time:
 - we need to set up environment isolation
 - Automated tests need to be better about relative filepaths (they can be run from anywhere in the project)
 - The `moldesign.yml` file needs an overhaul - the default_version_tag attribute shouldn't be user configurable, and clicking "apply" in the remote configurator shouldn't write *everything* to moldesign.yml, just the currently displayed remote engine

**Comment by justinmc** [comment]
✨ 🎆 🎉 🎈 ✨

**Pull request merged**
